### ISSUE TITLE
M7 ~ M9 datasets

### ISSUE THREAD

**Issue by huigoing** [PonderLY/PC-GNN#4]
hello authors:
 
  can you release M7 ~ M9 datasets by used in your paper, or  teach us how to generate such datasets?

thanks!

**Comment by PonderLY** [comment]
Hello，

Thanks for your interest. M7 ~ M9 are real-world datasets from Alibaba group and are not available publicly. The performance of PC-GNN can be validated on benchmarks like YelpChi and Amazon.

Thanks.
